AllCops:
  TargetRubyVersion: '2.5'
  Exclude:
    - boechat.gemspec

Lint/UselessAssignment:
  Exclude:
    - 'lib/boechat/version.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - '**/*_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
