# Describe all API healthcheck/status endpoints's that your application depends on!
services:
  - empresas:
      url: http://empresasservice.ad.vagastec.com.br/status
      status_endpoint: status
  - processos:
      url: http://qa-processosseletivosservice.ad.vagastec.com.br/healthcheck
      status_endpoint: healthcheck
