# Describe all API healthcheck/status endpoints's that your application depends on!
services:
  - name: empresas
    base_url: http://empresasservice.ad.vagastec.com.br
    status_endpoint: status
  - name: processos
    base_url: http://qa-processosseletivosservice.ad.vagastec.com.br
    status_endpoint: healthcheck
