#!/usr/bin/env ruby
# frozen_string_literal: true

require 'boechat'

aliases = { 'v' => 'verify', 'c' => 'console' }

command = ARGV.first
Boechat::Core::CommandRunner.call(aliases[command] || command)
